- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/mad_bot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"

- ros_topic_name: "/odom"
  gz_topic_name: "/model/mad_bot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "builtin_interfaces/msg/Time"
  gz_type_name: "ignition.msgs.Time"
